# Laptop Dataset Initial Data Understanding

This notebook contains the first stage of the project:
- loading the cleaned dataset
- checking structure and data types
- checking missing values and duplicates
- getting an initial understanding of the features

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [12]:
df = pd.read_csv("../data/raw/laptops_cleaned.csv")
df.head()

,brand,model,device_category,price,rating,cpu_brand,cpu_family,cpu_series,cpu_model,cpu_suffix,cpu_core_count,cpu_thread_count,cpu_p_cores,cpu_e_cores,cpu_lp_e_cores,ram_gb,storage_gb,display_width_px,display_height_px,display_size_inch,gpu_brand,gpu_series,gpu_model,gpu_vram_gb,gpu_type,os_name,warranty_years
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming,Gaming,189990,84,Intel,Core Ultra,Core Ultra 7,255HX,HX,20,20,8.0,12.0,NaN,32,1024,2560,1600,16,NVIDIA,GeForce RTX,RTX 5060,8.0,Dedicated,Windows,1
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN,Thin & Light,62350,54,Intel,Core,Core I5,13420H,H,8,12,4.0,4.0,NaN,16,1024,1920,1080,15,Intel,UHD,UHD Graphics,NaN,Integrated,Windows,1
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS,Thin & Light,34990,51,AMD,Ryzen,Ryzen 3,7320U,U,4,8,NaN,NaN,NaN,16,512,1920,1080,15,AMD,Radeon,Radeon,NaN,Integrated,Windows,1
3,lenovo,Lenovo V14 G3 82TS00JGUS,General,56990,48,Intel,Core,Core I7,1255U,U,10,12,2.0,8.0,NaN,16,512,1920,1080,14,Intel,Iris Xe,Iris Xe Graphics,NaN,Integrated,Windows,1
4,dell,Dell DC 14250 ODC1425000401RINS1,General,69990,52,Intel,Core,Core 5,120U,U,10,12,2.0,8.0,NaN,16,512,1920,1080,14,Intel,UHD,UHD Graphics,NaN,Integrated,Windows,1

In [13]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (992, 27)

Columns:
['brand', 'model', 'device_category', 'price', 'rating', 'cpu_brand', 'cpu_family', 'cpu_series', 'cpu_model', 'cpu_suffix', 'cpu_core_count', 'cpu_thread_count', 'cpu_p_cores', 'cpu_e_cores', 'cpu_lp_e_cores', 'ram_gb', 'storage_gb', 'display_width_px', 'display_height_px', 'display_size_inch', 'gpu_brand', 'gpu_series', 'gpu_model', 'gpu_vram_gb', 'gpu_type', 'os_name', 'warranty_years']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              992 non-null    object
 1   model              992 non-null    object
 2   device_category    992 non-null    object
 3   price              992 non-null    int64
 4   rating             992 non-null    int64
 5   cpu_brand          992 non-null    object
 6   cpu_family         992 non-null    object
 7   cpu_series         992 non-null    object
 8   cpu_model          992 non-null    object
 9   cpu_suffix         861 non-null    object
 10  cpu_core_count     992 non-null    int64
 11  cpu_thread_count   992 non-null    int64
 12  cpu_p_cores        703 non-null    float64
 13  cpu_e_cores        681 non-null    float64
 14  cpu_lp_e_cores     166 non-null    float64
 15  ram_gb             992 non-null    int64
 16  storage_gb         992 non-null    int64
 17  display_width_px   992 non-null    int64
 18  display_height_px  992 non-null    int64
 19  display_size_inch  992 non-null    int64
 20  gpu_brand          984 non-null    object
 21  gpu_series         984 non-null    object
 22  gpu_model          984 non-null    object
 23  gpu_vram_gb        292 non-null    float64
 24  gpu_type           984 non-null    object
 25  os_name            992 non-null    object
 26  warranty_years     992 non-null    int64
dtypes: float64(4), int64(10), object(13)
memory usage: 209.4+ KB

In [14]:
df.isnull().sum().sort_values(ascending=False)

cpu_lp_e_cores       826
gpu_vram_gb          700
cpu_e_cores          311
cpu_p_cores          289
cpu_suffix           131
gpu_model              8
gpu_series             8
gpu_type               8
gpu_brand              8
model                  0
brand                  0
cpu_core_count         0
cpu_model              0
cpu_series             0
cpu_family             0
rating                 0
cpu_brand              0
price                  0
device_category        0
display_height_px      0
display_width_px       0
storage_gb             0
ram_gb                 0
cpu_thread_count       0
display_size_inch      0
os_name                0
warranty_years         0
dtype: int64

In [7]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [8]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
brand,992,19,lenovo,233,NaN,NaN,NaN,NaN,NaN,NaN,NaN
model,992,992,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
device_category,992,5,General,390,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,992.0,NaN,NaN,NaN,87741.271169,68578.305994,12490.0,45912.5,67990.0,99240.0,605990.0
rating,992.0,NaN,NaN,NaN,59.918347,11.673423,27.0,52.0,59.0,66.0,98.0
cpu_brand,992,4,Intel,701,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cpu_family,992,7,Core,477,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cpu_series,992,24,Core I5,200,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cpu_model,992,119,13420H,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cpu_suffix,861,11,U,368,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cpu_core_count,992.0,NaN,NaN,NaN,9.576613,4.488597,2.0,6.0,8.0,10.0,24.0
cpu_thread_count,992.0,NaN,NaN,NaN,13.364919,5.616386,2.0,10.0,12.0,16.0,32.0
cpu_p_cores,703.0,NaN,NaN,NaN,4.045519,2.137224,0.0,2.0,4.0,6.0,10.0
cpu_e_cores,681.0,NaN,NaN,NaN,6.434655,3.023278,0.0,4.0,6.0,8.0,16.0
cpu_lp_e_cores,166.0,NaN,NaN,NaN,1.987952,1.044396,0.0,2.0,2.0,2.0,4.0
ram_gb,992.0,NaN,NaN,NaN,16.620968,7.521613,4.0,16.0,16.0,16.0,64.0
storage_gb,992.0,NaN,NaN,NaN,678.064516,382.160912,64.0,512.0,512.0,1024.0,6144.0
display_width_px,992.0,NaN,NaN,NaN,2047.360887,385.395084,1080.0,1920.0,1920.0,1920.0,3840.0
display_height_px,992.0,NaN,NaN,NaN,1215.15121,275.566927,720.0,1080.0,1080.0,1200.0,2400.0
display_size_inch,992.0,NaN,NaN,NaN,14.804435,0.89175,11.0,14.0,15.0,15.0,18.0
gpu_brand,984,5,Intel,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gpu_series,984,10,GeForce RTX,290,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gpu_model,984,38,UHD Graphics,188,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gpu_vram_gb,292.0,NaN,NaN,NaN,7.020548,3.538632,2.0,4.0,6.0,8.0,24.0
gpu_type,984,2,Integrated,692,NaN,NaN,NaN,NaN,NaN,NaN,NaN
os_name,992,6,Windows,930,NaN,NaN,NaN,NaN,NaN,NaN,NaN
warranty_years,992.0,NaN,NaN,NaN,1.094758,0.325649,1.0,1.0,1.0,1.0,3.0

In [9]:
numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = df.select_dtypes(exclude=np.number).columns.tolist()

print("Numeric columns:")
print(numeric_cols)

print("\nCategorical columns:")
print(categorical_cols)

Numeric columns:
['price', 'rating', 'cpu_core_count', 'cpu_thread_count', 'cpu_p_cores', 'cpu_e_cores', 'cpu_lp_e_cores', 'ram_gb', 'storage_gb', 'display_width_px', 'display_height_px', 'display_size_inch', 'gpu_vram_gb', 'warranty_years']

Categorical columns:
['brand', 'model', 'device_category', 'cpu_brand', 'cpu_family', 'cpu_series', 'cpu_model', 'cpu_suffix', 'gpu_brand', 'gpu_series', 'gpu_model', 'gpu_type', 'os_name']

In [10]:
for col in categorical_cols:
    print(f"\nColumn: {col}")
    print(df[col].value_counts(dropna=False).head(10))

Column: brand
brand
lenovo       233
hp           218
asus         179
acer         102
msi           93
dell          73
apple         22
samsung       17
microsoft     11
infinix       10
Name: count, dtype: int64

Column: model
model
Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming             1
Lenovo IdeaPad Slim 3 83K100HSIN                          1
Asus Vivobook Go 15 E1504FA-BQ2343WS                      1
Lenovo V14 G3 82TS00JGUS                                  1
Dell DC 14250 ODC1425000401RINS1                          1
Dell 14 Inspiron 5440 (100UU / 16GB / 512GB / Windows)    1
Lenovo V14 G4 82YTA00UIN                                  1
Acer TravelLite TL04-41M                                  1
HP Victus 15-fa2303tx Gaming                              1
HP Victus 15-fa1082wm Gaming                              1
Name: count, dtype: int64

Column: device_category
device_category
General         390
Gaming          258
Thin & Light    207
Business         78
Convertible      59
Name: count, dtype: int64

Column: cpu_brand
cpu_brand
Intel         701
AMD           230
Snapdragon     39
Apple          22
Name: count, dtype: int64

Column: cpu_family
cpu_family
Core          477
Ryzen         230
Core Ultra    192
Snapdragon     39
Celeron        30
M-Series       22
Core 5          2
Name: count, dtype: int64

Column: cpu_series
cpu_series
Core I5         200
Core I3         112
Core I7         106
Ryzen 5          90
Core Ultra 7     89
Ryzen 7          68
Core Ultra 5     58
Core Ultra 9     45
Snapdragon X     39
Celeron          33
Name: count, dtype: int64

Column: cpu_model
cpu_model
13420H    64
1315U     53
13620H    42
1334U     40
1215U     36
155H      33
1335U     28
N4500     25
125H      24
275HX     24
Name: count, dtype: int64

Column: cpu_suffix
cpu_suffix
U      368
H      282
NaN    131
HX     104
HS      54
V       42
Pro      4
G7       2
Max      2
Y        1
Name: count, dtype: int64

Column: gpu_brand
gpu_brand
Intel       488
NVIDIA      291
AMD         147
Qualcomm     38
Apple        20
NaN           8
Name: count, dtype: int64

Column: gpu_series
gpu_series
GeForce RTX            290
UHD                    188
Radeon                 147
Integrated Graphics    127
Arc                     95
Iris Xe                 73
Adreno                  38
Apple GPU               20
NaN                      8
HD                       5
Name: count, dtype: int64

Column: gpu_model
gpu_model
UHD Graphics           188
Radeon                 146
Integrated Graphics    127
Arc Graphics            95
Iris Xe Graphics        73
RTX 3050                73
RTX 4050                49
Adreno GPU              38
RTX 5060                24
RTX 2050                22
Name: count, dtype: int64

Column: gpu_type
gpu_type
Integrated    692
Dedicated     292
NaN             8
Name: count, dtype: int64

Column: os_name
os_name
Windows    930
DOS         24
Mac         22
Chrome      12
Ubuntu       3
Linux        1
Name: count, dtype: int64

In [11]:
missing_summary = df.isnull().sum()
missing_summary = missing_summary[missing_summary > 0].sort_values(ascending=False)

if missing_summary.empty:
    print("No missing values found.")
else:
    print(missing_summary)

cpu_lp_e_cores    826
gpu_vram_gb       700
cpu_e_cores       311
cpu_p_cores       289
cpu_suffix        131
gpu_brand           8
gpu_series          8
gpu_model           8
gpu_type            8
dtype: int64